name: CD pipeline for smoker vlapusik bot

env:
  APP_NAME: "smoker-vlapusik-bot"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to the server via ssh
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy
            if [ -d smoker-bot/.git ]; then
              echo "repository already exists, pulling changes..."
              cd $APP_NAME
              git pull origin master
            else
              echo "cloning repository for the first time"
              git clone https://github.com/ensomnatt/$APP_NAME
              cd $APP_NAME
            fi

            docker compose down
            docker compose up --build -d --remove-orphans
